language: python

python:
  - "3.9"
  - "3.7"

# Команда для установки зависимостей в окружение (при этом доступны переменные из секции "env")
install:
  - pip install -r requirements.txt --use-mirrors

# Команда для запуска тестов, в моем случае они запускаются именно так
script: pytest /tests